### ISSUE TITLE
Not Working on Godot 4 Release

### ISSUE THREAD

**Issue by yalazur** [godot-extended-libraries/godot-interpolated-camera3d#9]
Win Version: 11
Godot Version: 4

Steps:
New Project, Download the plugin, enable the pulgin, add plugin node, nothing shows up in Outliner.

**Comment by Calinou** [comment]
- Related to https://github.com/godot-extended-libraries/godot-interpolated-camera3d/issues/4.

> nothing shows up in Outliner.

What are you referring to by Outliner? There's no such thing in the Godot editor.

**Comment by yalazur** [comment]
I'm sorry for the confusion, I mean this bit 
![image](https://user-images.githubusercontent.com/113665849/226231511-9e8c8a09-50c7-4170-8d42-b845d3b3619d.png)

**Comment by Calinou** [comment]
The add-on's script has errors in 4.0.stable, but trying to add it as a node will not result in any feedback. (Someone should create a minimal reproduction and open an issue on godotengine/godot, since I consider this a bug.)

I'm working on updating the add-on and its demo so it works on 4.0.stable.

**Comment by Calinou** [comment]
Fixed: https://github.com/godot-extended-libraries/godot-interpolated-camera3d/releases/tag/v1.1.1
